version: '3'
services:
  nginx:
    platform: linux/x86_64
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    platform: linux/x86_64
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mariadb
    restart: always
    ports:
      - 13306:3306
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db